name:                corona
version:             0.1.0.0
github:              "nilsalex/corona"
license:             MIT
author:              "Nils Alex"
maintainer:          "nilsalex"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/corona#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- csv-conduit
- bytestring
- containers
- matplotlib

library:
  source-dirs: src

executables:
  corona-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corona
